apiVersion: 1

datasources:
  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: perf
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: perf-local-token
